rb_freq: 10
imu_freq: 50
heading_freq: 10
motor_freq: 10
flocking_freq: 10
range_n_bearing: {
  ambient: 30
}
avoidance_params: {
  d_thresh_obs: 0.8,
  d_thresh_rob: 1.0,
  K_p: 5,
  beta: 1.3,
  alpha: 1.0,
  gamma: 1.0,
  sigma_des_rob: 0.4,
  sigma_des_obs: 1.5,
  u_max: 0.3,
  C_obs: 1.0,
  C_rob: 1.5,
  offset_obs: 0,
  offset_rob: 0,
  zeta: 0.1,
}

# {C_obs: 1.0, C_rob: 1.0, K_p: 2, alpha: 1.0, beta: 0.8, d_thresh_obs: 0.8, d_thresh_rob: 1.0,
#   gamma: 1.0, offset_obs: 0, offset_rob: 0, sigma_des_obs: 1.5, sigma_des_rob: 0.45,
#   u_max: 0.2, zeta: 0.1}
